#THIS PAIR OF KEYS MUST BE DELETED AND NEW MUST BE GENERATED


def get_keys():
    KEY = "P4XXEIm3kmKKLwCmcnZTV3EZEJwnIqIlsmFODO6OJkTL1OJSERz9ypsk7QqvrClt"
    SECRET = "2JhJg04SDJxey3Y3TU2Nr3jIgy4ypgegECErZ3DDn0uv3DNN9EUGS1fnBzEIN4Eu"
    return KEY, SECRET